ALTER TABLE `customers`
  MODIFY `cnpj` VARCHAR(191) NULL,
  MODIFY `legalName` VARCHAR(191) NULL,
  MODIFY `whatsapp` VARCHAR(191) NULL,
  MODIFY `street` VARCHAR(191) NULL,
  MODIFY `number` VARCHAR(191) NULL,
  MODIFY `district` VARCHAR(191) NULL,
  MODIFY `city` VARCHAR(191) NULL,
  MODIFY `state` VARCHAR(191) NULL;
